### PR TITLE
Ben/re implement

### PR DESCRIPTION
**Pull request by blugavere**

### CODE REVIEW

**Comment by Angelk90** [comment]
@blugavere : 

I did a test there seems to be some problem:

1) An attribute is added named `field:" ... "`.
2) If the attribute is of the required type, the attribute is also added to the obj.
3) Attributes are added that in the declared model there are no `_id` and `__v`.
4) A "required": [] attribute is added to scopes, which should not be there.

```json
{
  "definitions": {
    "ApiKeyModel": {
      "title": "ApiKey",
      "required": [
        "owner"
      ],
      "properties": {
        "owner": {
          "type": "string",
          "required": true,
          "description": "Owner user"
        },
        "apiKey": {
          "type": "string",
          "field": "apiKey"
        },
        "expiration": {
          "type": "string",
          "format": "date-time",
          "field": "expiration"
        },
        "active": {
          "type": "boolean",
          "field": "active"
        },
        "scopes": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "scope": {
                "type": "string",
                "enum": [
                  "user",
                  "geo_area",
                  "apikey"
                ]
              },
              "actions": {
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "create",
                    "read",
                    "update",
                    "delete"
                  ]
                }
              }
            },
            "required": []
          },
          "field": "scopes"
        },
        "_id": {
          "type": "string",
          "field": "_id"
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time",
          "field": "updatedAt"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "field": "createdAt"
        },
        "__v": {
          "type": "number",
          "field": "__v"
        }
      }
    },
    "UserModel": {
      "title": "User",
      "required": [],
      "properties": {
        "name": {
          "type": "string",
          "field": "name"
        },
        "surname": {
          "type": "string",
          "field": "surname"
        },
        "_id": {
          "type": "string",
          "field": "_id"
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time",
          "field": "updatedAt"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "field": "createdAt"
        },
        "__v": {
          "type": "number",
          "field": "__v"
        }
      }
    }
  }
}
```

**Comment by blugavere** [comment]
image
Thanks for the feedback Angel! Check the latest commit - seems to be working OK

**Comment by Angelk90** [comment]
@blugavere :

I tried it seems there are still some problems:
- A name attribute is inserted, "_id" string that I didn't put in the model
- If there are no required elements, advisors not to enter it, something like this is generated: "required": []
- The latter is also required as a scope attribute, which is not very correct, because it shouldn't have it.


If you could create a way online that I could try my model by trying it out it would be an interesting thing.

```

{
  "definitions": {
    "ApiKeyModel": {
      "title": "ApiKey",
      "required": [
        "owner"
      ],
      "properties": {
        "owner": {
          "type": "string",
          "description": "Owner user"
        },
        "apiKey": {
          "type": "string"
        },
        "expiration": {
          "type": "string",
          "format": "date-time"
        },
        "active": {
          "type": "boolean"
        },
        "scopes": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "scope": {
                "type": "string",
                "enum": [
                  "user",
                  "geo_area",
                  "apikey"
                ]
              },
              "actions": {
                "type": "array",
                "items": {
                  "type": "string",
                  "enum": [
                    "create",
                    "read",
                    "update",
                    "delete"
                  ]
                }
              }
            },
            "required": []
          }
        },
        "_id": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "UserModel": {
      "title": "User",
      "required": [],
      "properties": {
        "name": {
          "type": "string"
        },
        "surname": {
          "type": "string"
        },
        "_id": {
          "type": "string"
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time"
        }
      }
    }
  }
}
```

**Comment by blugavere** [comment]
_id is auto-generated from mongo docs, its present in the data
"required": [] is valid swagger (albiet un-necessary since the array is empty) - is it causing a problem or are you concerned only with the JSON size?

**Comment by Angelk90** [comment]
@blugavere :
`_id` is generated of which mongo docs do you speak?
Besides worrying about the size, if you have the model that I proposed to you as an example in scopes, there should be no attribute  `"required": []`.

**Comment by Angelk90** [comment]
@blugavere : Are there any news?

**Comment by blugavere** [comment]
published mongoose-to-swagger @ 1.0

**Pull request merged**
